rate limit

diff --git a/.github/workflows/terraform-ci.yml b/.github/workflows/terraform-ci.yml
--- a/.github/workflows/terraform-ci.yml
+++ b/.github/workflows/terraform-ci.yml
@@ -19,230 +19,230 @@ permissions:
 
 jobs:
 
-  lint:
-    name: Lint (terraform fmt, validate, tflint)
-    runs-on: ubuntu-latest
-    outputs:
-      lint_status: ${{ steps.lint_check.outcome }}
-    steps:
-      - name: Checkout repo
-        uses: actions/checkout@v4
+  # lint:
+  #   name: Lint (terraform fmt, validate, tflint)
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #     lint_status: ${{ steps.lint_check.outcome }}
+  #   steps:
+  #     - name: Checkout repo
+  #       uses: actions/checkout@v4
 
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          aws-region: ${{ env.AWS_REGION }}
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
+  #     - name: Configure AWS Credentials
+  #       uses: aws-actions/configure-aws-credentials@v2
+  #       with:
+  #         aws-region: ${{ env.AWS_REGION }}
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
 
-      - name: Setup Terraform CLI
-        uses: hashicorp/setup-terraform@v2
-        with:
-          terraform_version: ${{ env.TERRAFORM_VERSION }}
+  #     - name: Setup Terraform CLI
+  #       uses: hashicorp/setup-terraform@v2
+  #       with:
+  #         terraform_version: ${{ env.TERRAFORM_VERSION }}
 
-      - name: Setup tflint
-        uses: terraform-linters/setup-tflint@v1
-        with:
-          version: ${{ env.TFLINT_VERSION }}
+  #     - name: Setup tflint
+  #       uses: terraform-linters/setup-tflint@v1
+  #       with:
+  #         version: ${{ env.TFLINT_VERSION }}
 
-      - name: Terraform Init
-        run: terraform init -input=false
-        working-directory: infrastructure
+  #     - name: Terraform Init
+  #       run: terraform init -input=false
+  #       working-directory: infrastructure
 
-      - name: Run tflint
-        id: tflint_check
-        run: |
-          set -e
-          tflint --init
-          tflint || exit 1
-        working-directory: infrastructure
+  #     - name: Run tflint
+  #       id: tflint_check
+  #       run: |
+  #         set -e
+  #         tflint --init
+  #         tflint || exit 1
+  #       working-directory: infrastructure
 
-      - name: Comment tflint results on PR if failed
-        if: failure()
-        uses: GetTerminus/terraform-pr-commenter@v2
-        with:
-          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-          comment_type: error
-          comment_message: |
-            tflint failed. Please fix the errors before merging.
+  #     - name: Comment tflint results on PR if failed
+  #       if: failure()
+  #       uses: GetTerminus/terraform-pr-commenter@v2
+  #       with:
+  #         github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+  #         comment_type: error
+  #         comment_message: |
+  #           tflint failed. Please fix the errors before merging.
 
-      - name: Auto-format Terraform files
-        run: terraform fmt -recursive
-        working-directory: infrastructure
+  #     - name: Auto-format Terraform files
+  #       run: terraform fmt -recursive
+  #       working-directory: infrastructure
 
-      - name: Terraform fmt check
-        id: fmt_check
-        run: |
-          terraform fmt -check -recursive
-        working-directory: infrastructure
+  #     - name: Terraform fmt check
+  #       id: fmt_check
+  #       run: |
+  #         terraform fmt -check -recursive
+  #       working-directory: infrastructure
 
-      - name: Comment terraform fmt results if failed
-        if: failure()
-        uses: GetTerminus/terraform-pr-commenter@v2
-        with:
-          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-          comment_type: error
-          comment_message: |
-            terraform fmt check failed. Please format your code.
+  #     - name: Comment terraform fmt results if failed
+  #       if: failure()
+  #       uses: GetTerminus/terraform-pr-commenter@v2
+  #       with:
+  #         github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+  #         comment_type: error
+  #         comment_message: |
+  #           terraform fmt check failed. Please format your code.
 
-      - name: Terraform validate
-        id: validate_check
-        run: terraform validate
-        working-directory: infrastructure
+  #     - name: Terraform validate
+  #       id: validate_check
+  #       run: terraform validate
+  #       working-directory: infrastructure
 
-      - name: Comment terraform validate results if failed
-        if: failure()
-        uses: GetTerminus/terraform-pr-commenter@v2
-        with:
-          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-          comment_type: error
-          comment_message: |
-            terraform validate failed. Please fix the configuration.
+  #     - name: Comment terraform validate results if failed
+  #       if: failure()
+  #       uses: GetTerminus/terraform-pr-commenter@v2
+  #       with:
+  #         github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+  #         comment_type: error
+  #         comment_message: |
+  #           terraform validate failed. Please fix the configuration.
 
-      - name: Lint Check Output
-        id: lint_check
-        run: echo "Lint completed"
+  #     - name: Lint Check Output
+  #       id: lint_check
+  #       run: echo "Lint completed"
 
-  security_scan:
-    name: Security Scan (tfsec)
-    runs-on: ubuntu-latest
-    needs: lint
-    outputs:
-      security_status: ${{ steps.tfsec_check.outcome }}
-    steps:
-      - name: Checkout repo
-        uses: actions/checkout@v4
+  # security_scan:
+  #   name: Security Scan (tfsec)
+  #   runs-on: ubuntu-latest
+  #   needs: lint
+  #   outputs:
+  #     security_status: ${{ steps.tfsec_check.outcome }}
+  #   steps:
+  #     - name: Checkout repo
+  #       uses: actions/checkout@v4
 
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          aws-region: ${{ env.AWS_REGION }}
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
+  #     - name: Configure AWS Credentials
+  #       uses: aws-actions/configure-aws-credentials@v2
+  #       with:
+  #         aws-region: ${{ env.AWS_REGION }}
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
 
-      - name: Setup Terraform CLI
-        uses: hashicorp/setup-terraform@v2
-        with:
-          terraform_version: ${{ env.TERRAFORM_VERSION }}
+  #     - name: Setup Terraform CLI
+  #       uses: hashicorp/setup-terraform@v2
+  #       with:
+  #         terraform_version: ${{ env.TERRAFORM_VERSION }}
 
-      - name: Terraform Init
-        run: terraform init -input=false
-        working-directory: infrastructure
+  #     - name: Terraform Init
+  #       run: terraform init -input=false
+  #       working-directory: ./infrastructure
 
-      # - name: Run tfsec scan and comment results on PR
-      #   id: tfsec_check
-      #   uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
-      #   with:
-      #     github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+  #     # - name: Run tfsec scan and comment results on PR
+  #     #   id: tfsec_check
+  #     #   uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
+  #     #   with:
+  #     #     github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
 
-      # - name: Run tfsec via reviewdog
-      #   uses: reviewdog/action-tfsec@v1
-      #   with:
-      #     github_token: ${{ secrets.GITHUB_TOKEN }}
-      #     reporter: github-pr-review        
-      #     filter_mode: nofilter              
-      #     fail_on_error: false
+  #     # - name: Run tfsec via reviewdog
+  #     #   uses: reviewdog/action-tfsec@v1
+  #     #   with:
+  #     #     github_token: ${{ secrets.GITHUB_TOKEN }}
+  #     #     reporter: github-pr-review        
+  #     #     filter_mode: nofilter              
+  #     #     fail_on_error: false
       
-      - name: Check using tfsec and comment Results on PR
-        id: tfsec
-        uses: tfsec/tfsec-pr-commenter-action@v1.3.1
-        with:
-          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-          working_directory: infrastructure
+  #     - name: Check using tfsec and comment Results on PR
+  #       id: tfsec
+  #       uses: tfsec/tfsec-pr-commenter-action@v1.3.1
+  #       with:
+  #         github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+  #         working_directory: infrastructure
 
-  plan:
-    name: Terraform Plan
-    runs-on: ubuntu-latest
-    needs: [lint, security_scan]
-    if: ${{ needs.lint.result == 'success' && needs.security_scan.result == 'success' }}
-    outputs:
-      plan_result: ${{ steps.plan_comment.outcome }}
-    steps:
-      - name: Checkout repo
-        uses: actions/checkout@v4
+  # plan:
+  #   name: Terraform Plan
+  #   runs-on: ubuntu-latest
+  #   needs: [lint, security_scan]
+  #   if: ${{ needs.lint.result == 'success' && needs.security_scan.result == 'success' }}
+  #   outputs:
+  #     plan_result: ${{ steps.plan_comment.outcome }}
+  #   steps:
+  #     - name: Checkout repo
+  #       uses: actions/checkout@v4
 
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          aws-region: ${{ env.AWS_REGION }}
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
-          role-session-name: terraform-plan
+  #     - name: Configure AWS Credentials
+  #       uses: aws-actions/configure-aws-credentials@v2
+  #       with:
+  #         aws-region: ${{ env.AWS_REGION }}
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
+  #         role-session-name: terraform-plan
 
-      - name: Setup Terraform CLI
-        uses: hashicorp/setup-terraform@v2
-        with:
-          terraform_version: ${{ env.TERRAFORM_VERSION }}
+  #     - name: Setup Terraform CLI
+  #       uses: hashicorp/setup-terraform@v2
+  #       with:
+  #         terraform_version: ${{ env.TERRAFORM_VERSION }}
 
-      - name: Terraform Init EC2
-        run: terraform init -input=false
-        working-directory: infrastructure/terraform-ec2
+  #     - name: Terraform Init EC2
+  #       run: terraform init -input=false
+  #       working-directory: infrastructure/terraform-ec2
 
-      - name: Terraform Plan EC2
-        run: terraform plan -no-color -out=tfplan-ec2.binary
-        working-directory: infrastructure/terraform-ec2
+  #     - name: Terraform Plan EC2
+  #       run: terraform plan -no-color -out=tfplan-ec2.binary
+  #       working-directory: infrastructure/terraform-ec2
 
-      - name: Terraform Plan Show EC2
-        run: terraform show -no-color tfplan-ec2.binary > plan.txt
-        working-directory: infrastructure/terraform-ec2
-
-
-      - name: Comment EC2 plan on PR
-        uses: actions/github-script@v7
-        with:
-          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-          script: |
-            const fs = require('fs');
-            const plan = fs.readFileSync('infrastructure/terraform-ec2/plan.txt', 'utf8');
-            github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: `## Terraform Plan Output for \`terraform-ec2\`
-              \n\n\`\`\`hcl\n${plan}\n\`\`\``
-              });
+  #     - name: Terraform Plan Show EC2
+  #       run: terraform show -no-color tfplan-ec2.binary > plan.txt
+  #       working-directory: infrastructure/terraform-ec2
 
 
-      - name: Terraform Init S3
-        run: terraform init -input=false
-        working-directory: infrastructure/terraform-s3
+  #     - name: Comment EC2 plan on PR
+  #       uses: actions/github-script@v7
+  #       with:
+  #         github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+  #         script: |
+  #           const fs = require('fs');
+  #           const plan = fs.readFileSync('infrastructure/terraform-ec2/plan.txt', 'utf8');
+  #           github.rest.issues.createComment({
+  #             issue_number: context.issue.number,
+  #             owner: context.repo.owner,
+  #             repo: context.repo.repo,
+  #             body: `## Terraform Plan Output for \`terraform-ec2\`
+  #             \n\n\`\`\`hcl\n${plan}\n\`\`\``
+  #             });
 
-      - name: Terraform Plan S3
-        run: terraform plan -no-color -out=tfplan-s3.binary
-        working-directory: infrastructure/terraform-s3
 
-      - name: Terraform Plan Show S3
-        run: terraform show -no-color tfplan-s3.binary > plan-s3.txt
-        working-directory: infrastructure/terraform-s3
+  #     - name: Terraform Init S3
+  #       run: terraform init -input=false
+  #       working-directory: infrastructure/terraform-s3
 
-      - name: Comment S3 Plan on PR
-        uses: actions/github-script@v7
-        with:
-          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-          script: |
-            const fs = require('fs');
-            const plan = fs.readFileSync('infrastructure/terraform-s3/plan-s3.txt', 'utf8');
-            github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: `## Terraform Plan Output for \`terraform-s3\`
-              \n\n\`\`\`hcl\n${plan}\n\`\`\``
-              });
+  #     - name: Terraform Plan S3
+  #       run: terraform plan -no-color -out=tfplan-s3.binary
+  #       working-directory: infrastructure/terraform-s3
 
-      - name: Upload EC2 and S3 plan artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          name: terraform-plans
-          path: |
-            infrastructure/terraform-ec2/tfplan-ec2.binary
-            infrastructure/terraform-s3/tfplan-s3.binary
+  #     - name: Terraform Plan Show S3
+  #       run: terraform show -no-color tfplan-s3.binary > plan-s3.txt
+  #       working-directory: infrastructure/terraform-s3
+
+  #     - name: Comment S3 Plan on PR
+  #       uses: actions/github-script@v7
+  #       with:
+  #         github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+  #         script: |
+  #           const fs = require('fs');
+  #           const plan = fs.readFileSync('infrastructure/terraform-s3/plan-s3.txt', 'utf8');
+  #           github.rest.issues.createComment({
+  #             issue_number: context.issue.number,
+  #             owner: context.repo.owner,
+  #             repo: context.repo.repo,
+  #             body: `## Terraform Plan Output for \`terraform-s3\`
+  #             \n\n\`\`\`hcl\n${plan}\n\`\`\``
+  #             });
+
+  #     - name: Upload EC2 and S3 plan artifacts
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: terraform-plans
+  #         path: |
+  #           infrastructure/terraform-ec2/tfplan-ec2.binary
+  #           infrastructure/terraform-s3/tfplan-s3.binary
 
   build_artifact:
     name: Build Artifact
     runs-on: ubuntu-latest
-    needs: plan
-    if: ${{ needs.plan.result == 'success' }}
+    # needs: plan
+    # if: ${{ needs.plan.result == 'success' }}
     outputs:
       new_release_tag: ${{ steps.tag_release.outputs.new_release_tag }}
     steps:
